### ISSUE TITLE
[bug] problem with raspberry V2

### ISSUE THREAD

**Issue by ClaudioAl** [ranjib/reef-pi#137]
Rasp V2
uname -a: Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux
VERSION="8 (jessie)"
Hardware        : BCM2835

i2cdetect -y 1:
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --

reef-pi -version: 0.0.4

ERROR: Failed to sync equipment:Return Error:embd: your host ": ARMv7 Processor rev 5 (v7l)" is not supported at this moment. request support at https://github.com/kidoman/embd/issues

**Comment by ranjib** [comment]
@ClaudioAl Fixed by https://github.com/ranjib/reef-pi/pull/139
I'll make a debian build and release it soon
